#!/bin/bash 

NUMCORES=`getconf _NPROCESSORS_ONLN`
JSYNC=`echo $(( $NUMCORES * 2 ))`         

#Setup proper path to rid missing gcc warning
PATH=$PATH:/home/zaitower/AndroidDev/AAtoolchains/SaborMod/aarch64-linux-gnu-5.3/bin

#Keep thangs sqeaky
echo
echo
echo " Makin thangs squeaky clean "
make clean
make mrproper

#Keep thangs sqeaky
echo
echo
echo " Making out directory "
mkdir -p out

#xxx= Your config name
echo
echo
echo " Run defconfig "
make ARCH=arm64 CROSS_COMPILE=/home/zaitower/AndroidDev/AAtoolchains/SaborMod/aarch64-linux-gnu-5.3/bin/aarch64- O=out elementalx_defconfig -j$JSYNC

#Change arm-eabi- to what you current toolchain uses default is gcc4.6 & gcc4.7 toolchains
echo
echo
echo " Set to arm at 375, for about 20 to 40 minutes "
make ARCH=arm64 CROSS_COMPILE=/home/zaitower/AndroidDev/AAtoolchains/SaborMod/aarch64-linux-gnu-5.3/bin/aarch64- O=out -j$JSYNC

